version: '2'

services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.17
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"

  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
    depends_on:
      - db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./run_celery.sh"]
    volumes:
      - .:/webapps
    links:
      - db
      - rabbit
    depends_on:
      - db
      - rabbit
