version: '2'

services:
  test_api:
    build: .
    volumes:
      - .:/webapps
    command: ["./run_tests.sh"]
    environment:
    - PYTHONWARNINGS=ignore
    - DJANGO_SETTINGS_MODULE=customers_api.settings_test
